### ISSUE TITLE
Suggestion - Import online CC

### ISSUE THREAD

**Issue by BoomOSRS** [MarbleTurtle/FriendsExporter#4]
Not an issue, I've used the plugin as intended several times and it has proven useful - Thank you :)

Would it be possible to export player names and ranks of people currently in the clan chat?
It would be a great feature for community clans to compile several of these lists to check activity levels to review ranks.

**Comment by MarbleTurtle** [comment]
To confirm you are asking that the ranks be added to the current members export? Currently it is setup so that it can export the members in cc but I did not think to include ranks as it was more for logging general activity rather than specific ranks but it should be simple to add if desired.

**Comment by BoomOSRS** [comment]
Honestly, it looks like I was asking for a feature that already existed. 
Ranks not required as you said, I just wanted to log general activity but only just discovered that I could do that today.
Please ignore me - And thank you very much for the plugin. Works brilliantly 👍
